name: Example Maven workflow with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Or your desired distribution
          java-version: '11'        # Or whichever version you're using

      - name: Run Snyk to check for vulnerabilities in Maven dependencies
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Code Test for security issues in source code
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
