name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
      
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Set environment variable for Snyk
        run: echo "SNYK_TOKEN=${{ secrets.SNYK_TOKEN }}" >> $GITHUB_ENV

      - name: Build with maven
        run: mvn clean package

      - name: Run Snyk Code Test for SQL Injection
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
