name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if your project uses Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (if applicable)
        run: npm install
        working-directory: ./

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v3
        with:
          args: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to test for vulnerabilities
        uses: snyk/actions@v3
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
