name: SpotBugs 

on:
  push:
    branches: [ main ]

jobs:
    spotbugs:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        # set up java
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            java-version: '1.8'

        # build project with maven
            - name: Build with maven
            - run: mvn clean package
        
        # run SpotBugs
            - name: Run SpotBugs
            - mvn spotbugs:check
        
