name: SpotBugs with FindSecBugs

on:
  push:
    branches: [ main ]

jobs:
    spotbugs:
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        security-events: write
        
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        # this needs to be appropriately configured for your project
        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            distribution: 'microsoft'
            java-version: 11

        # now run SpotBugs and upload the results to Code Scanning
        - name: Run SpotBugs with FindSecBugs
          uses: advanced-security/spotbugs-findsecbugs-action@v1
          with:
            spotbugs_target: 'src/main/java/com/test/dao' # cannot have globs
