name: Snyk Security Scan for Java
on:
  push:
    branches:
main
  pull_request:
    branches:
main
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
name: Checkout code
        uses: actions/checkout@v3

name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

name: Build with Maven
        run: mvn -B package --file pom.xml

name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@v3
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

name: Monitor the project with Snyk
        uses: snyk/actions/maven@v3
        with:
          args: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
