name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Code Test for security issues in source code
        run: snyk code test 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
